### ISSUE TITLE
Swapped labels of figure in Readme?

### ISSUE THREAD

**Issue by romanhaa** [yanailab/enhance#1]
Really interesting work. I'm just wondering about the labels in the figure of the Readme. Shouldn't "Raw data" and "ENHANCE" be written on the side rather than on top?

![figure](https://user-images.githubusercontent.com/18103560/58943273-b217a080-877f-11e9-9d3a-36cd295a10a6.png)

And since I'm here: Am I right to assume that the output of ENHANCE won't be a sparse matrix anymore?

**Comment by flo-compbio** [comment]
Thanks Roman, of course you're right, the figures were swapped!

**Comment by flo-compbio** [comment]
The figure is fixed, but I think due to caching GitHub is still showing the old version.

**Comment by flo-compbio** [comment]
OK, I see the correct figure now.
